### PR TITLE
Use pkg-config to fix cross-compilation

### PR DESCRIPTION
**Pull request by joerg-krause**
libupnp and libcurl both provide a .pc file. Use pkg-config so that the
correct library pathes are used to link against the dependencies of
libupnp and libcurl.

Otherwise, in case of cross-compilation, libupnpp tries to link against
the host libraries in `/usr/lib` and not the cross-compiled libraries in
`sysroot`, e.g. (the last line are the libs libupnp is dependent of):

```
-L/usr/arm-buildroot-linux-musleabi/sysroot/usr/lib -lexpat -lcurl
-L/usr/arm-buildroot-linux-musleabi/sysroot/usr//lib -lssl -lcrypto -lz -lupnp
-L/usr/lib -lthreadutil -lixml -lpthread -lrt
```

Note, that this adds a dependency on pkg-config to libupnpp.

### CODE REVIEW

**Comment by medoc92** [comment]
I think that the CHECK_LIB against libixml is spurious, I am going to remove it. There is a comment 5 lines above saying it should not be there...

I don't understand where the -lthreadutil and -lixml parameters are coming from in your trace. It seems to me that only -lupnp should be in there ? libixml may be there because of the test I am going to remove, but where does -lthreadutil come from ?

Also: there were issues with the configure.ac "future" patch (future was actually never detected), I'm going to commit a change.

**Comment by joerg-krause** [comment]
> I don't understand where the -lthreadutil and -lixml parameters are coming from in your trace. It seems to me that only -lupnp should be in there ?

They come from the [pkg-config file](https://sourceforge.net/p/pupnp/code/ci/master/tree/libupnp.pc.in) of libupnp.

> Also: there were issues with the configure.ac "future" patch (future was actually never detected)...

Sorry, I tested the compilation of the snippet with my host g++ which compiled without any errors whereas the cross-compiler aborted.

As this PR has conflicts, I will update it soon.

**Comment by joerg-krause** [comment]
> I think that the CHECK_LIB against libixml is spurious, I am going to remove it.

You're right, libixml is save to remove as it is a dependency of libupnp.

**Comment by medoc92** [comment]
Oops, I now think that my ixml change was wrong. libupnpp does use libixml directly (not through libupnp), so I guess that libixml should really be in the link. 

But as far as I understand, it is going to be provided by the pkg-config output anyway, so it would seem reasonable to just add the PKG_ lines. Let me try this and see what I get.

**Comment by medoc92** [comment]
Ok. so, after checking, PKG_CONFIG does not really work for me. On my system it adds a spurious -L/usr/local/lib.

Also, when using PKG_CONFIG, LIBS is not directly updated: the libs to add are stored in a variable named libupnp_LIBS (in the case of your change), which then needs to be added to the libs (or otherwise used). 

So I committed what is I think the correct version: explicitely link with libupnp and libixml, because they are directly used.

We should them find the reason why the cross-compile does not work, I don't think that this is because of AC_CHECK_LIB. There is no reason for things to work with libexpat and not libupnp.

**Comment by joerg-krause** [comment]
> Oops, I now think that my ixml change was wrong. libupnpp does use libixml directly (not through libupnp), so I guess that libixml should really be in the link.

Where does libupnpp uses libixml directly? I don't think so.

> But as far as I understand, it is going to be provided by the pkg-config output anyway, so it would seem reasonable to just add the PKG_ lines. Let me try this and see what I get.

Yes, if pkg-config is used for libupnp.

> Also, when using PKG_CONFIG, LIBS is not directly updated: the libs to add are stored in a variable named libupnp_LIBS (in the case of your change), which then needs to be added to the libs (or otherwise used).

I will check this.

**Comment by medoc92** [comment]
J�rg Krause writes:
 >     Oops, I now think that my ixml change was wrong. libupnpp does use libixml
 >     directly (not through libupnp), so I guess that libixml should really be in
 >     the link.
 > 
 > Where does libupnpp uses libixml directly? I don't think so.

There are dozens of calls to ixml... interfaces actually. Just grep for
them, e.g.:
./control/service.cxx:        if (*rqpp) ixmlDocument_free(*rqpp);

**Comment by joerg-krause** [comment]
Yes, but they are included from `upnp/ixml.h` so it uses ixml indirectly through libupnp.

**Comment by joerg-krause** [comment]
I updated the commit. `expat` provides a .pc file, too, so I added it. I removed ixml as it is a dependency of libupnp. I fixed the issue that the dependencies are not properly added to `LIBS`.

**Comment by medoc92** [comment]
J�rg Krause writes:
 > Yes, but they are included from upnp/ixml.h so it uses ixml indirectly through
 > libupnp.

No, you are mixing compiling and linking issues. I have to link
libupnpp with libixml explicitely, else I get undefined symbols when I try
to build upmpdcli. I could add libixml to the upmpdcli link to fix this,but
it makes no sense, it's better to link it with libupnpp.

Actually I'll add -no-undefined to the libupnpp link, it should always had
been there. Like this we can be sure that we do the right thing, else we
get error there and then.

**Comment by joerg-krause** [comment]
This is why upmpdcli should use pkg-config to link against libupnpp. The dependency ixml will be propagated properly to upmpdcli.

**Comment by joerg-krause** [comment]
Using this commit I get the following `LIBUPNPP_LIBS`:

```
checking for UPNP... yes
checking for CURL... yes
checking for EXPAT... yes
checking for getifaddrs... yes
checking for UpnpSetLogLevel... no
LIBUPNPP_LIBS -lpthread -lrt  -pthread -lupnp -lthreadutil -lixml -lcurl -lexpat
```

So using pkg-config for libupnp does add `-lixml` to the `LIBUPNPP_LIBS`.

**Comment by medoc92** [comment]
J�rg Krause writes:
 > This is why upmpdcli should use pkg-config to link against libupnpp. The
 > dependency ixml will be propagated properly to upmpdcli.
 > 

But upmpdcli must not be linked against libixml, because it does not use it
directly, only through libupnpp.

So all is currently correct, and I'm not changing anything we just need to
find out why cross-compiling does not work.

**Comment by joerg-krause** [comment]
> But upmpdcli must not be linked against libixml, because it does not use it
directly, only through libupnpp.

Yes, this is true for a shared build. However, for a static build the dependencies must be propagated to upmpdcli. Currently, this is not supported. Please have a look at the build issue for [libupnpp](http://autobuild.buildroot.net/results/f38/f383bf4d7572a7dd59d382cd06a9baeb37e9161c/build-end.log) with the corresponding [report](http://lists.busybox.net/pipermail/buildroot/2015-May/128256.html) and for [upmpdcli](http://autobuild.buildroot.net/results/7ed/7ed85071bc06b4806e90b278a0736ea70c01b456/build-end.log) with the corresponding [report](http://lists.busybox.net/pipermail/buildroot/2015-August/135822.html).

So the usage of pkg-config ensures that always the correct libs and pathes are used for both shared and dynamic linking.

**Comment by joerg-krause** [comment]
I did some investigations why the wrong library path is selected. libtool does not use the correct sysroot path for the dependency libs *threadutil* and *ixml*:

`dependency_libs` in libupnpp.la:
```
dependency_libs='
/home/buildroot/output/host/usr/x86_64-buildroot-linux-musl/sysroot/usr/lib/libexpat.la
/home/buildroot/output/host/usr/x86_64-buildroot-linux-musl/sysroot/usr/lib/libcurl.la
/home/buildroot/output/host/usr/x86_64-buildroot-linux-musl/sysroot/usr/lib/libixml.la
/home/buildroot/output/host/usr/x86_64-buildroot-linux-musl/sysroot/usr/lib/libupnp.la
/home/buildroot/output/build/libupnp-1.6.20/threadutil/libthreadutil.la
/home/buildroot/output/build/libupnp-1.6.20/ixml/libixml.la -lpthread -lrt
/home/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/x86_64-linux-musl/5.3.0/../../../../x86_64-linux-musl/lib/libstdc++.la'
```

`libdir` in /home/buildroot/output/build/libupnp-1.6.20/threadutil/libthreadutil.la:
```
# Directory that this library needs to be installed in:
libdir='/usr/lib'
```

`libdir` in /home/buildroot/output/host/usr/x86_64-buildroot-linux-musl/sysroot/usr/lib/libthreadutil.la:
```
# Directory that this library needs to be installed in:
libdir='/home/joerg/Development/git/buildroot/output/host/usr/x86_64-buildroot-linux-musl/sysroot/usr/lib'
```

I have no clue why libtool does not detect the correct sysroot path for *threadutil* and *ixml*.

**Comment by joerg-krause** [comment]
Certainly a libtool issue!

The libtool version "2.4.2 Debian-2.4.2-1.11" bundled in the download package works, as well as a patched libtool version from Buildroot, whereas with a cloned git version, the libtool version "2.4.6" generated by `libtoolize` does not.

The dependency_libs in libupnpp.la are the same for all libtool versions, so I guess some internal function makes the difference.

There is an old [thread](https://lists.gnu.org/archive/html/libtool/2010-02/msg00000.html) about issues with libtool. As Buildroot and Debian still patches libtool in version 2.4+ it seems there are issues with libtool when cross-compiling.

These cross-compiler issues can be easily resolved by using pkg-config for getting the correct pathes.

**Comment by joerg-krause** [comment]
The issue with the generated libtool from autogen.sh happens when libtool installs the libtool library into the sysroot directory running:

```
make DESTDIR=/home/buildroot/output/host/usr/x86_64-buildroot-linux-musl/sysroot install -C /home/buildroot/output/build/libupnpp/
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   libupnpp.la '/home/buildroot/output/host/usr/x86_64-buildroot-linux-musl/sysroot/usr/lib'

```

**Comment by medoc92** [comment]
Joerg, I would prefer that you keep this as a packaging patch. It's not like the configure.ac is going to change much or often.

The problem I have with it is that pkgconfig actually adds another source of problems. For example, on my Ubuntu 16.04 machine, here is what it says (--libs) for libupnp:

    -L/usr/local/lib -pthread -lupnp -lthreadutil -lixml

The /usr/local/lib bit is obviously wrong and a potential source of mysterious issues. 

Do you really have a need for static linking ? I can surely devise other approaches for solving this.

**Comment by joerg-krause** [comment]
I tested `pkg-config --libs libupnp` on a Ubuntu 16.04 machine and it tells me:

```
-pthread -lupnp -lthreadutil -lixml
```

Do you have a local version of libupnp installed?

> Do you really have a need for static linking ?

I prefer static linking if I need to build a package for an embedded system where the package is not available and the libraries are not up to date. For example some Pandora device still use glibc 2.13. It is much easer to build a static linked executable, e.g. upmpdcli, than fetching all the necessary libraries with their correct versions.

**Comment by medoc92** [comment]
Had another look at why pkg-config was listing /usr/local on my system, and this was because of a leftover .pc file in /usr/local, due to an incomplete cleanup of an old installation of libupnp to /usr/local. So only the .pc file remained, but no problem for pkg-config, it picked it up in priority anyway.

I think that this illustrates quite well the issue with pkg-config: it may be convenient at times, but it is a source of additional issues.

I think that it might be worth to give a try to implementing a --enable-static flag to the upmpdcli configure.ac

When you do a static link, are all libs linked static  (meaning I can just set -Wl,-Bstatic as a link flag and list the libs), or just a subset ?

**Comment by medoc92** [comment]
Thinking again, this is going to be complicated, because some libs we indirectly depend on, such as libcurl->libgnu-tls->etc. have long and complicated dependancies themselves.

So actually, patching configure.ac to use pkg-config when you want a static link does appear like a rather good solution ! Or I could check if it is feasible to conditionally use PKG_CHECK... when --enable-static is set ?

**Comment by joerg-krause** [comment]
I do not think it is an issue if pkg-config picks up a leftover .pc file from an incomplete cleanup. In your case, nothing goes wrong if /usr/local/lib is passed to the linker as an addition library to search for the libraries.

However, pkg-config does work, if the .pc file is correct, for a shared and static build as well as for host- and cross-compilation. libtool seems to have some issues with cross-compilation and it needs proper handling for static linking.

Regardings my commit: Unfortunately, it does not fix the unsafe library path issue. I checked the cross build again and it looks I used the Debian version of libtool by not running in a clean libupnpp source directory from a git clone.

So, I am unsure, if this issue can be fixed at all outside from patching libtool. I asked for advice on the Buildroot mailing list.

I had a look at the MPD build scripts. MPD does not use libtool and the build of MPD with linking against libupnp was successful. Maybe libtool can be replaced?

That said, despite the commit does not fix the unsafe library path issue, I think it improves the linking of libupnpp.

**Comment by joerg-krause** [comment]
On second thought, MPD is not a library and obviously does not need libtool. So forget about this one...

**Comment by joerg-krause** [comment]
Using pkg-config solely does not help to fix **this** issue of unsafe header/library paths. A patched libtool is necessary! I do not want to burden the autogen script to do so, so I'll leave it to the user to do so when cross-compiling from the git clone.

However, as the commit fixes static build issues, I will open a new pull request and leave this one for reference.

**Pull request closed without merging**
